#!/bin/sh

set -e

daemon=${1:?}
state="%{F#b47f6f}off%{F-}"
cmd="$(systemctl status $daemon | grep -i run 2>/dev/null || echo '')"

[[ "$cmd" ]] && state="%{F#b7b0d1}on%{F-}"

echo "%{F#4c2777}${daemon} : %{F-} ${state}"
exit 0
